XWORLD Licenses
===============
Guenther Brunthaler
v2025.66

[Please mind the comment at the end of this text about its source 
format if you need to edit the text.]

This repository contains a selection of software and 
documentation licenses which are referenced from various projects 
of the 'XWORLD'-realm developer collective.

The idea is that all those projects reference this repository as 
an external repository which is, logically, part of the source 
tree. This avoids duplication of the license notices in all the 
main projects which use the same license.

In case of the 'Git DVCS' submodules can be used as such external 
references.

But make sure that the licenses are referred to by name in your 
source files, or it will be unclear which of the license files 
actually apply to each source file or other type of licensed 
document.

Alternatively, put a small `LICENSE.TXT` or similarly named file 
into the top-level directory of your project tree and state 
clearly there which of the licenses in the external project apply 
to the whole project by default.

[Format of the source form of this text: 66 columns, ASCII 
character set, continuation lines within the same logical 
paragraph are indicated by the last character of the previous 
line being an ASCII space character, right before the newline.]
